### PR TITLE
Upgrade firebase/jwt-token up to ^6.0

### PR DESCRIPTION
**Pull request by syl20b**
Hi there,

I started to work on the upgrade of the firebase/jwt-token version  ( CF #120).

Regards,

### CODE REVIEW

**Comment by joanna-bak-sourceability** [comment]
@christeredvartsen could you approve the workflow. We need that fix as well...

**Comment by vitxd** [comment]
Any chance this can be merged? Is this project still active and maintained?

**Comment by syl20b** [comment]
> Any chance this can be merged? Is this project still active and maintained?

@christeredvartsen ?

**Comment by christeredvartsen** [comment]
@syl20b @joanna-bak-sourceability @vitxd @magikid

I have created a branch that will bump the `firebase/jwt-token` version along with other dependencies. If that branch works for you I can push a new major version of this package.

You can test the branch using `dev-bump-deps` in your composer.json file.

Please use #125 for further discussion.

**Comment by Aurelieluciani** [comment]
@christeredvartsen Is it possible to have a version with only the upgrade of the firebase/jwt-token to 6.4? So it will be compatible with PHP 8.0

**Comment by christeredvartsen** [comment]
@Aurelieluciani Just tagged `v3.0.2` with your PR. Thanks!

**Pull request closed without merging**
