### PR TITLE
Add Oauth 2 JWT token support

### PR DESCRIPTION
**Pull request by Zwartpet**
Added a method to test JWT tokens

### CODE REVIEW

**Comment by Zwartpet** [comment]
According to travis the build is succeeded: https://travis-ci.org/imbo/behat-api-extension but gitlab is waiting for the status.

**Comment by christeredvartsen** [comment]
I noticed. Tried to re-run the Travis-build, but it didn't help.

**Comment by Zwartpet** [comment]
So can this be merged?

**Comment by christeredvartsen** [comment]
> So can this be merged?

I will try to look through it later today to see if I can merge it.

**Comment by christeredvartsen** [comment]
Currently it's only possible to match a JWT that is in the first level of the JSON response. If the response contains for instance:

```json
{
  "some": {
    "nested": {
      "object": {
        "with": {
          "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ"
        }
      }
    }
  }
}
```

It would be great if one could m atch this as well, also values in numericallly indexed arrays. Perhaps use a notation like `some.nested.object.with.jwt` (to match the above example), and also support `[<index>]` to be able to match JWTs in lists?

**Comment by christeredvartsen** [comment]
It would be nice to be able to use the `Then the response body contains JSON:` step, and perhaps add a `@jwt()` custom matcher function. Since these "functions" doesn't handle nested objects as params, as this could generate invalid JSON, we could create another step which holds the decoded JWT and give them an identifier, which we then could reference in the `@jwt()` matcher.

Then we could do something like this:

```gherkin
Then the response body contains a JWT identified by "some JWT reference":
    """
    {
      "header": {
        "alg": "HS256",
        "typ": "JWT"
      },
      "claims": {
        "sub": "some subject",
        "iss": "some issuer"
      },
      "secret": "some secret"
    }
    """
And the response body contains JSON:
    """
    {
        "some": {
            "object": {
                "with": {
                    "value": "@jwt(some JWT reference)"
                }
            }
        }
    }
    """
```

The two steps can then be used together to be able to match JWTs placed anywhere in the body. Does this sound OK @Zwartpet?

**Comment by Zwartpet** [comment]
Sounds good to me, i'm not able to update the code in the upcoming days though. Probably after the weekend.

**Comment by christeredvartsen** [comment]
I can push to your branch though, so I can hack together something tonight.

**Comment by Zwartpet** [comment]
Then I'll keep an eye on my inbox to see you're implementation ;)

**Comment by Zwartpet** [comment]
Looks good, is there anything else need to be done?

**Pull request merged**
