### PR TITLE
Upgrade firebase php jwt

### PR DESCRIPTION
**Pull request by mnofresno**
You previously gently created a new tag v2.3.2 for us. We're currently working on upgrading firebase/php-jwt dependency on our project.

Could you please create a new tag v2.3.3 for us with that change?

Thank you very much!!

### CODE REVIEW

**Comment by christeredvartsen** [comment]
You need to update the composer.lock file as well. You can probably just do:

    composer update --no-install

**Comment by mnofresno** [comment]
You're right @christeredvartsen Fixed! thank you!

**Review by christeredvartsen — APPROVED** [review]

**Comment by christeredvartsen** [comment]
The change fails the unit tests. Could you fix that @mnofresno so that I can generate a release?

**Comment by mnofresno** [comment]
Thank you very much @christeredvartsen sorry for the delay. Can you please guide me on how to check the tests that failed on Github? I'll fix them ASAP.

**Comment by christeredvartsen** [comment]
I forgot about this one. Pushed a fix now, and released `v2.3.3`.

**Pull request merged**
