### PR TITLE
Add 7.0 Guzzle Compatibility

### PR DESCRIPTION
**Pull request by mnofresno**
In our company we use Behat Imbo API extension.

In order to be able to update GuzzleHttp we need this change to be done in v2.x of the IMBO/Behat API extension library.

Thanks!

### CODE REVIEW

**Comment by mnofresno** [comment]
Additional question:

who could or how I could create and push the tag 2.3.2 on this repo if the PR is approved?

**Comment by christeredvartsen** [comment]
Could you please see if the `v2.x` branch works for you now? I did some more changed since the branch was being tested at Travis CI, which I no longer want to use.

**Comment by christeredvartsen** [comment]
If everything seems to be working I can push a new version in the 2.x range.

**Comment by christeredvartsen** [comment]
I have created and pushed the `v2.3.2` tag based on the current state of the `v2.x` branch. The commits in this PR does not add anything relevant to the release and will be closed.

Hopefully the `v2.3.2` release will work for you.

**Pull request closed without merging**
