### PR TITLE
Require PHP 7.4

### PR DESCRIPTION
**Pull request by christeredvartsen**
This PR will bump the minimum requirement to PHP >= 7.4. All dependencies have been updated as well.

### CODE REVIEW

**Comment by christeredvartsen** [comment]
@ghola Care to test this branch and see if it meets your needs before we merge it back to `develop`?

**Comment by alex-farcas** [comment]
I tested it on two of my projects and it seems to be working as expected. I see you incorporated the changes from my PR. Can I cancel mine?

**Comment by ghola** [comment]
I tested it on two of my projects and it seems to be working as expected. I see you incorporated the changes from my PR. Can I cancel mine?

**Comment by christeredvartsen** [comment]
Yes, I closed the existing PR. I co-authored you in the main commit in this PR (bde06cb), hope that was OK.

**Comment by ghola** [comment]
Sure, that is OK.

**Comment by ghola** [comment]
@christeredvartsen Can you please make a 3.* release for this?

**Comment by christeredvartsen** [comment]
@ghola Sure, I can do a release in a few days.

**Pull request merged**
