### PR TITLE
Move docs currently in README elsewhere

### PR DESCRIPTION
**Pull request by christeredvartsen**
This PR is work in progress with regards to moving the docs currently found in README.md elsewhere. As the number of steps increase the README file is not good enough as a source of documentation.

### CODE REVIEW

**Comment by christeredvartsen** [comment]
Currently I have only added docs for a couple of steps using Read the docs to see how it looks.

The docs currently written can be found here: http://behat-api-extension.readthedocs.io/en/issue-36-docs/

Do you have any feedback regarding this @Alex-D? Do you think moving the docs to Read the docs is an improvement? Current I only added two steps there, but you can see the outline and how TOCs are generated and so forth.

**Comment by Alex-D** [comment]
It seems to be a good idea since there is a search bar and a summary :)

**Comment by Alex-D** [comment]
For the moment, the doc is here: http://behat-api-extension.readthedocs.io/en/develop

**Comment by christeredvartsen** [comment]
Correct. It will stay that way until an official release includes the docs, then `/en/latest` will point to that release.

**Pull request merged**
