### PR TITLE
Check individual payload properties instead of whole array

### PR DESCRIPTION
**Pull request by Zwartpet**
Its almost impossible to test generated payload values like the expired the way the JWT matcher works.
I suggest checking the properties that are given in the jwt token you want to check.

### CODE REVIEW

**Comment by Zwartpet** [comment]
Created new pull request because I messed up my own fork.

**Comment by christeredvartsen** [comment]
How about we manage to inject the array comparator into the JWT matcher, so it can use the same matching as regular objects? That way we would be able to recursively match JWTs, and use the regular expression matching to parts of the payload as well.

**Comment by Zwartpet** [comment]
Thats how I wanted to implement it at first, but I thought you had a reason not to inject the comparater. But yea assumptions are deadly, will update the code later today.

**Comment by Zwartpet** [comment]
Bump

**Comment by christeredvartsen** [comment]
Will have a look in a couple of days, slightly busy at the moment.

**Comment by christeredvartsen** [comment]
I think this PR is ready to be merged. Could you have a glance and give :+1: or :-1: @Zwartpet?

**Pull request merged**
