### PR TITLE
Allow jwt version 4 also since the differences are minor 

### PR DESCRIPTION
**Pull request by pwolanin**
Other libraries may not have updated their requirements

### CODE REVIEW

**Comment by Zwartpet** [comment]
That would limit 5 to <=5.0 though

**Comment by pwolanin** [comment]
https://getcomposer.org/doc/articles/versions.md

says:

```1.0 - 2.0``` is equivalent to ```>=1.0.0 <2.1```

**Comment by christeredvartsen** [comment]
One other option would be `^4.0 | ^5.0` for instance.

**Comment by pwolanin** [comment]
Sure, changed it to that syntax.

**Pull request merged**
